name: C CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: |
          sudo apt update
          sudo apt install libopenmpi-dev -yyq
    - name: debug_build
      run: make clean && make CFLAGS+=-Werror
    - name: release_build
      run: make clean && make release CFLAGS+=-Werror
    - name: tests
      run: make test
